server:
  port: 8764
  servlet:
    context-path: /provider-coolkid

spring:
  application:
    name: provider-coolkid
  cloud:
    config:
      enabled: false
  session:
    store-type: redis
  data:
    redis:
      host: 10.10.173.54
      password: admin
      port: 6379
      database: 4

logging:
  level:
    root: INFO

app:
  config:
    eureka:
      port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${app.config.eureka.port}/eureka/
